// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SubmitPositionOnChangeController from "./submit_position_on_change_controller"
application.register("submit-position-on-change", SubmitPositionOnChangeController)
